# Generated by Django 5.1.5 on 2025-02-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='character',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
